[install]
linker = "isolated"

[test]
coveragePathIgnorePatterns = [
  "**/dist/**",
  "**/command/preset/actions/**",
  "**/*.{test,spec,bench,benchmark}.ts",
]
coverageReporter = [
  "text",
  "lcov"
]
