[tools]
# Environments
node = 'latest'
'github:nubjs/nub' = 'latest'
# Linters & Formatters
hk = 'latest'
stylua = 'latest'
pkl = 'latest'

[deps.nub]
description = 'Automatically install Node.js dependencies via nub.'
sources = ['package.json', 'nub.lock']
outputs = ['node_modules/']
run = 'nub pm pin && nub install'
auto = true

[env]
_.path = ['{{config_root}}/node_modules/.bin']

# See https://github.com/webpro-nl/knip/issues/1813 & https://github.com/oxc-project/oxc/issues/11834
KNIP_DISABLE_RAW_TRANSFER = 1

[tasks.dev]
description = "Run the development server with hot reloading."
usage = '''
flag "--pwa" help="Whether to enable PWA support."
'''
run = "{{ 'VITE_PLUGIN_PWA=true' if usage.pwa else '' }} nuxt dev --open --public"

[tasks.build]
description = "Run the production build."
usage = '''
flag "--static" help="Whether to build the static site."
'''
run = "nuxt {{ 'generate' if usage.static else 'build' }}"

[tasks.start]
description = "Start the production server."
usage = '''
flag "--static" help="Whether to start the static site."
'''
run = "{{ 'serve .output/public' if usage.static else 'nub .output/server/index.mjs' }}"

[tasks.check]
description = 'Run all checks.'
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk check {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''

[tasks.fix]
description = 'Fix all check issues.'
usage = '''
flag "-s --staged" help="Run on staged files only without stashing unstaged changes"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
hk fix {{ "--staged" if usage.staged else "--all" }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''

[tasks.pretest]
run = "playwright-core install --with-deps"

[tasks.test]
description = "Run tests."
depends = ["build", "pretest"]
usage = '''
flag "-w --watch" help="Watch files for changes and rerun tests"
arg "[rest]" var=#true help="Additional arguments to pass to the test runner"
'''
run = '''
vitest {{ '' if usage.watch else 'run' }} {{ usage.rest | join(sep=' ') if usage.rest else '' }}
'''
