packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.6.5
    '@nuxt/eslint': ^1.9.0
    '@nuxt/fonts': ^0.11.4
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/device': ^3.2.4
    '@nuxtjs/i18n': ^10.1.1
    '@nuxtjs/seo': ^3.2.2
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.4
    '@unocss/nuxt': ^66.5.4
    '@vite-pwa/nuxt': ^1.0.6
    '@vueuse/nuxt': ^13.9.0
    dayjs-nuxt: ^2.1.11
    nuxt: ^4.1.3
    nuxt-echarts: ^1.0.1
    nuxt-qrcode: ^0.4.8
    nuxt-svgo: ^4.2.6
    nuxt-swiper: ^2.0.1
    unocss: ^66.5.4
  dev:
    '@antfu/eslint-config': ^6.0.0
    czg: ^1.12.0
    eslint: ^9.37.0
    eslint-plugin-format: ^1.0.2
    lint-staged: ^16.2.4
    simple-git-hooks: ^2.13.1
    taze: ^19.7.0
    typescript: ^5.9.3
    vue-tsc: ^3.1.1
  frontend:
    '@vueuse/core': ^13.9.0
    dayjs: ^1.11.18
    echarts: ^6.0.0
    pinia: ^3.0.3
    vue: ^3.5.22
    vue-echarts: ^8.0.1
  icons:
    '@iconify-json/carbon': ^1.2.14
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

verifyDepsBeforeRun: install
shellEmulator: true
