packages: []

catalogs:
  build:
    '@nuxt/devtools': ^2.6.3
    '@nuxt/eslint': ^1.9.0
    '@nuxt/image': ^1.11.0
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/device': ^3.2.4
    '@nuxtjs/i18n': ^10.1.0
    '@pinia/nuxt': ^0.11.2
    '@unocss/eslint-config': ^66.5.1
    '@unocss/nuxt': ^66.5.1
    '@unocss/preset-web-fonts': ^66.5.1
    '@vite-pwa/nuxt': ^1.0.4
    '@vueuse/nuxt': ^13.9.0
    dayjs-nuxt: ^2.1.11
    nuxt: ^4.1.1
    nuxt-svgo: ^4.2.6
    nuxt-typed-router: ^4.0.2
    unocss: ^66.5.1
  dev:
    '@antfu/eslint-config': ^5.3.0
    czg: ^1.12.0
    eslint: ^9.35.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^16.1.6
    simple-git-hooks: ^2.13.1
    taze: ^19.6.0
    typescript: ^5.9.2
    vue-tsc: ^3.0.6
  frontend:
    '@vueuse/core': ^13.9.0
    dayjs: ^1.11.18
    pinia: ^3.0.3
    vue: ^3.5.21
  icons:
    '@iconify-json/carbon': ^1.2.13
    '@iconify-json/twemoji': ^1.2.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
